### ISSUE TITLE
CMake Solution Idea

### ISSUE THREAD

**Issue by reapazor** [dotBunny/CLionSourceCodeAccess#10]
Well I've been trying to come up with a good way to do this generation of the project, and then it hit me ... use UBT to produce into a format i can cross convert. 

Looking at the CodeLite format now, which ill parse the created files and then convert them into a CMakeList.

BAM! :)

**Comment by reapazor** [comment]
Implemented in 06a2849d473674e36419671acbc81f36c5c3391d

**Comment by M-Pixel** [comment]
Mostly out of curiosity, why was UBT's CMakefileGenerator not used? What about it doesn't work with CLion?

**Comment by reapazor** [comment]
So the stock UBT generation of make files isnt compatible with CLion.
It's being worked on though :)
