### ISSUE TITLE
Add Hotswap Ability

### ISSUE THREAD

**Issue by reapazor** [dotBunny/CLionSourceCodeAccess#12]
Ability to compile code inside of IDE and swap into Unreal.

**Comment by RicardoEPRodrigues** [comment]
Any release date for this feature?

Tired of having to switch to Unreal to compile :smile:

**Comment by reapazor** [comment]
I hear ya :)

@anastasiak2512 from JetBrains has been working on cleaning up the Windows side of things :) I'll build on her work as soon as I/we can find some free time.

I really want this to work too ... I'm just swamped atm.

**Comment by reapazor** [comment]
It actually works already, just have to use it a certain way. Going to do a video me thinks showing it off.

**Comment by RicardoEPRodrigues** [comment]
I watched your video and it is awesome.

Yet in Linux the Hot Swap is not working. Do I have to do any extra steps to activate that ability?

**Comment by RicardoEPRodrigues** [comment]
I know I'm being annoying, but I really like this plugin and want it to work!

**Comment by reapazor** [comment]
Honestly its perfectly OK :)
I'm not sure how to do that on Linux ... it should naturally work assuming that the UBT works from within CLion. 

For me to really debug this, i'd have to install UE on another VM. We'll see ... see how it shakes down in the priority list. As I'm trying to get a version available on the marketplace (precompiled), I do need to work out these cases.

**Comment by RicardoEPRodrigues** [comment]
I can't get it to work. I always need to compile in editor. When you have the time please give it a look. Maybe I'm doing something wrong.

I started UE4 from CLion by modifying the `Editor-Development` to have `UE4Editor` as executable, the `.project` as a parameter and the engine folder as the working directory. Should I add anything more?

**Comment by RicardoEPRodrigues** [comment]
I've watched and re-watched the [integration video](https://vimeo.com/214201769) and I can't get it to work.

Still no HotReload...

**Comment by reapazor** [comment]
Are you building (command f9) or running? (ie the play button doesnt work)

**Comment by reapazor** [comment]
Im literally streaming it right now :)

**Comment by RicardoEPRodrigues** [comment]
Link please!

I tried everything. 

* Running the editor, opening CLion through the editor and only then building in CLion (command f9).
* Running CLion, debugging the editor and then building in CLion (command f9).
* Running CLion, running the editor through CLion (play button) and then building in CLion (command f9).

Nothing works...

**Comment by reapazor** [comment]
https://www.twitch.tv/reapazor

**Comment by RicardoEPRodrigues** [comment]
I'm watching! :smile:

**Comment by RicardoEPRodrigues** [comment]
The solution you've proposed (adding HotReload to `Build.cs`) didn't work, but I think you are right that Unreal does not load HotReload module for the accessor, more like it loads the module but ignores it.

I looked in the logs and found this:

    LogHAL: Linux SourceCodeAccessSettings: NullSourceCodeAccessor

I think it ignores the module because the Linux default is the NullSourceCodeAccessor. I'll try changing it and see what happens.
