### ISSUE TITLE
LogCLionAccessor:Error: Unable to find [ProjectName]CodeCompletionFolders.txt

### ISSUE THREAD

**Issue by DarthIwan** [dotBunny/CLionSourceCodeAccess#13]
Hi,

first of all, many thanks for the plugin! :)

Unfortunately, I have an issue regarding generating CMakeList.txt. As mentioned in this post header, I'm getting this message every time I'm trying to generate the CMakeList.txt. Any ideas what I'm doing wrong or is it a bug?

I'm working on MacOS El Capitan 10.11.6 MacBook Pro 13" Retina.

Best,
Sergej

**Comment by reapazor** [comment]
The way the plugin works currently is that it dumps out a CodeLite project file and parses it. Its looking for that file which is created during that process.

When you look at your project folder is there any addition .project or other files having been made? 

PS. Im happy to see others start using it... i haven't had a chance to test on multiple systems yet so this is FANTASTIC :)

**Comment by DarthIwan** [comment]
Hi, 

thank you for very quick help :D

I can't see any new files in project folder. Still just *.uproject file and standard folders.

Best,
Sergej

**Comment by reapazor** [comment]
What version of unreal ? source or installed?

**Comment by DarthIwan** [comment]
4.12.5, installed :)

**Comment by reapazor** [comment]
hmmm --- very strange, is there any special characters in the path to the project?

**Comment by DarthIwan** [comment]
I've thought about that, but not tested yet. But indeed, I have a space in the name, maybe thats the problem. I'll test it and report here the result.

**Comment by reapazor** [comment]
Awesome, thanks...

**Comment by DarthIwan** [comment]
Yep, it was my fault. The reason for the error was space in folder name. Now all works fine. Thanks for your support :)

Best,
Sergej

**Comment by reapazor** [comment]
I'm promoting this to a bug to fix (spaces in names and how to handle them)

**Comment by reapazor** [comment]
Fixed in recent pushes.
