### ISSUE TITLE
Plugin compilation isn't triggered at the start on Windows

### ISSUE THREAD

**Issue by Maririri** [dotBunny/CLionSourceCodeAccess#16]
After setting up the plugin on macOS I was eager to try it on Windows, but performing the same steps (creating Plugins folder with sources inside) and restarting editor doesn't trigger compilation.
As a result I see CLion plugin in the list, but no dedicated actions or settings. How can I understand what is wrong?
note: my path to project doesn't contain whitespaces.

**Comment by reapazor** [comment]
Something I've found specifically to do with this is if you do not have any "source" in your project files it will not actually know to compile plugins. 

This is shown when you add a new plugin, or actually cant from within UE ... unless you've got a source code file in the project. There must be something to do with that and the project settings.

I will investigate though :)

**Comment by SirJackblue** [comment]
I recently setup this amazing plugin on a project, and even if you set the plugin inside the "Plugins" folder, right click on .uproject and select "generate visual studio project", once you recompile your project the plugin is available on the plugins list but you can't set CLion as Source Code editor or modify plugin's settings.

You need to go to the plugin list, and click "Package..", chose a folder to package the plugin, close your editor, remplace your plugin by this new packaged version and you are ready to go :)

**Comment by reapazor** [comment]
@JohnsonJackblue Did you have any other code files in your project at the time? 

I had a weird occurrence where a new project (all BP) would not even look in the plugins folder until I added a c++ code file to the project.

I haven't had a chance to do any testing on platforms outside of mac (i know right?), so you guys are the bleeding edge support here :)

**Comment by SirJackblue** [comment]
@reapazor Yeah I created a C++ project.

And yes a BP only project need a packaged plugin (or a plugin with compiled source will work too) to work without a developer's workspace, while you don't have any source code your project is BP even if Visual Studio is already install.

For the support, if you don't have any Windows devices, maybe setup a Virtual machine can be a solution :)

**Comment by tontinton** [comment]
I didn't understand the solution. Can you please explain yourself once more?

**Comment by SirJackblue** [comment]
Go to the plugins menu:
![1](http://image.prntscr.com/image/7e37164420604754bf2545d4e70762e9.png)

Select the "Programming" category (where CLion plugin is) and click "Package..":
![2](http://image.prntscr.com/image/c57242a3acb4490ea4a35d280a0baa90.png)

Select a location to save the new packaged plugin, close your editor, remplace the old CLionSourceCodeAccess plugin by the new "Packaged" one on your "Plugins" folder

**Comment by tontinton** [comment]
I don't have that option though.

**Comment by SirJackblue** [comment]
That's strange, have you installed Visual Studio ?

**Comment by tontinton** [comment]
Yes

**Comment by tontinton** [comment]
Here's how it looks like:
![ss 2016-10-23 at 10 58 54](https://cloud.githubusercontent.com/assets/19514176/19629056/6e3b9a70-9974-11e6-84ef-02a1ae3fb6d7.png)

**Comment by SirJackblue** [comment]
It's look like you added the plugin directly to your engine installation and not on your project, simply create a "Plugins" folder on your unreal project and add this plugin, don't forget to remove the plugin on your Unreal Engine installation.

Normally you will see project's plugins, on a different tab at the bottom.

Edit: You can add it to your Engine installation once you package it, actually your plugin is not compiled.

**Comment by tontinton** [comment]
Thanks for your help, but i am still having a problem with packaging:
![ss 2016-10-23 at 11 21 18](https://cloud.githubusercontent.com/assets/19514176/19629194/7c7a04d4-9977-11e6-848b-dad227c8745e.png)

**Comment by SirJackblue** [comment]
Oh yeah there is an useless local variable and VS can't compile the plugin, you can see it here :
![1](http://image.prntscr.com/image/c4d4890bf85a40deb56f40bc2bd8c624.png)

Well simply remove this variable:
https://github.com/dotBunny/CLionSourceCodeAccess/blob/master/Source/CLionSourceCodeAccess/Private/CLionSourceCodeAccessor.cpp#L199

And it will be ok :)

**Comment by tontinton** [comment]
Alright!
Thanks for everything

**Comment by reapazor** [comment]
Hmm thats odd - that shouldnt cause an error. I will remove that tho :)

**Comment by SirJackblue** [comment]
@reapazor thanks !

**Comment by hgmich** [comment]
Can you check if the latest version fixes this? I had similar issues that were resolved by the changes made.

**Comment by onelson** [comment]
@ceph3us It's working for me currently.

**Comment by reapazor** [comment]
I'd thought I'd circle back on this issue -- is it still happening or did removing that extra variable resolve the issue?

**Comment by reapazor** [comment]
It seems this most often is caused 9/10 times by someone trying to use the plugin on a non code based project (so you created a new project as a blueprint project, and do not have any c++ files int he project).

I've now added a notice to the wiki.

**Comment by somelun** [comment]
Hello, guys. I have the same problem. I added already packaged plugin to my c++ project (but plugin's folder still contain "Source" folder). I see CLion Integration plugin as installed, bat can't setup environment. Thanks for any help!
