### ISSUE TITLE
Add set(CMAKE_CXX_STANDARD 11) to generated CMakeLists.txt

### ISSUE THREAD

**Issue by Maririri** [dotBunny/CLionSourceCodeAccess#17]
Probably it should be read from UE project compiler flag settings, but seems like it doesn't as it fails to compile decltype().

**Comment by reapazor** [comment]
I'll see about adding this :) Most likely tomorrow.

**Comment by reapazor** [comment]
Just a heads up, was talking with a dev from JetBrains, looks like she is gonna push a PR with fixes for this, and some other optimization to the plugin (im hopeful!)
