### ISSUE TITLE
Two windows open after Unreal generates code.

### ISSUE THREAD

**Issue by Zerophase** [dotBunny/CLionSourceCodeAccess#21]
Generating a new C++ class causes CLion to open two windows, instead of one window with tabs for the header and cpp file generated.

Sometimes I get an error message about a `tmp` file not existing, and only one window opens for the header.

**Comment by reapazor** [comment]
This is linux again?

**Comment by Zerophase** [comment]
yep.

**Comment by reapazor** [comment]
I've committed a fix for this, basically making a single open call to CLion for different files. (876292ade6025c646d3a7810099b5ca811eebe90)
