### ISSUE TITLE
After enabling the plugin, I don't see CLion as an option for the code editor.

### ISSUE THREAD

**Issue by tontinton** [dotBunny/CLionSourceCodeAccess#22]
From UE4 editor:
Editor Preferences -> Source Control -> Accessor -> _ONLY Visual Studio here_

**Comment by reapazor** [comment]
Do you have any code in your project? 
The plugin doesn't get compiled currently without an actual addition of code to the project (creating a workspace, etc).

This is an Unreal side limitation. 
I'm looking for a way around it.

**Comment by tontinton** [comment]
I have code in my project, I just opened the FirstPerson example given when creating a new project.

**Comment by reapazor** [comment]
The first person BP or first person C++ template?

**Comment by tontinton** [comment]
C++

**Comment by reapazor** [comment]
when you shutdown unreal and restart the project does it ask you to compile the plugin then? _has it asked you to compile it yet?_

**Comment by tontinton** [comment]
It doesn't ask me to compile the plugin.
It opens normally without any questions.

**Comment by SirJackblue** [comment]
You need to package it, I explain here how you can do it : https://github.com/dotBunny/CLionSourceCodeAccess/issues/16#issuecomment-255363351

**Comment by hgmich** [comment]
This should be fixed with #25, which I couldn't get the plugin to load in Unreal without on Windows in my source copy.
