### ISSUE TITLE
Error Opening Clion on Mac

### ISSUE THREAD

**Issue by cajun-code** [dotBunny/CLionSourceCodeAccess#24]
I have created a project with UE 4.10.4. 
Created a Plugins directory and loaded the CLion Plugin into the project.  
When i click on generate CMakeList file or Open CLion in the menu.  
I get this message. 
LogCLionAccessor:Error: Unable to find /Users/alley/Projects/clownwars/clownwarsCodeCompletionFolders.txt

It looks like the version of CodeLite is the problem, which is 1.0 beta of the plugin.

**Comment by reapazor** [comment]
The plugin doesn't actually use the beta plugin for CodeLite with Unreal, it uses UE's build systems output feature to CodeLite and then parses that setup for the files it needs.

Is there anything in your unreal log files when you go to generate the CMakeLIsts from the menu?

**Comment by reapazor** [comment]
Inactivity :(
