### ISSUE TITLE
Opens Two CLion Windows in MacOSX 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [dotBunny/CLionSourceCodeAccess#27]
I don't know what's the error but whenever we try open any component(cpp file). It opens two CLion IDEs 

![twoclion](https://cloud.githubusercontent.com/assets/8083613/20227502/955e4dca-a872-11e6-90d4-3a3fad7ad8d1.gif)

**Comment by PaEl94** [comment]
Same on Linux. If there isn't already an instance open, two new ones get opened when trying to edit any cpp file.

**Comment by reapazor** [comment]
So this appears to be a recent development, when launching with a CLion instance already running it absorbs and closes the others as it recognizes the file load.

But if you dont have CLIon open i see it opening two ... working on it it :)

**Comment by reapazor** [comment]
^ Aint I funny :) *sigh*

**Comment by reapazor** [comment]
The reason it opens "two" instances is because Unreal now opens not only the Header File, as well as the CPP file, so its sending out two open requests. <looking into solution>

**Comment by reapazor** [comment]
Fixed in 876292ade6025c646d3a7810099b5ca811eebe90
