### ISSUE TITLE
doesn't recognise Unreal CPP code 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [dotBunny/CLionSourceCodeAccess#28]
As in case of xcode we can't build the project directly from within CLion because CLion shows error in cpp code. Can't to figure out why it doesn't recognise unreal symbols. Even after processing everything.

![errorcode](https://cloud.githubusercontent.com/assets/8083613/20227731/a73eb16e-a873-11e6-83de-bc33ea1f1189.gif)

**Comment by RicardoEPRodrigues** [comment]
I have the same problem.

**Comment by RicardoEPRodrigues** [comment]
Even with the UE4 plugin for CLion, the code gives errors and the autocomplete is lacking. It really demotivates me from using the plugin...

@reapazor do you have these issues?

**Comment by reapazor** [comment]
Sadly I do not ... as seen in the video from a while ago:
https://vimeo.com/214201769

**Comment by RicardoEPRodrigues** [comment]
From what I see, it seems that CLion doesn't take into consideration some generated files from the UE4 build. Some weird files like `file.generated.dep.h`.

Reopening CLion fixes the issue, it's a bit annoying, but I think it only happens when creating a new class.

**Comment by reapazor** [comment]
I've now seen this happen randomly in the most recent EAP. It seems to do with CLion itself sadly. I'm closing this as its not related to the plugin.
