### ISSUE TITLE
Generator uses backslashes on windows

### ISSUE THREAD

**Issue by SkaveRat** [dotBunny/CLionSourceCodeAccess#30]
When generating the cmake files, the absolute paths are generated with backslashes. Replacing them with forward slashes seems to fix loading the project on a windows machine

**Comment by reapazor** [comment]
_duh_ 

/me smacks self in face.

**Comment by mjrogozinski** [comment]
I've created pull request fixing this issue.

**Comment by SkaveRat** [comment]
PR fixed it on my end
