### ISSUE TITLE
ArchLinux UnrealEngine 4.13 problem

### ISSUE THREAD

**Issue by Pierre-Green** [dotBunny/CLionSourceCodeAccess#31]
Hello when I try to load the CLionSourceCodeAccess
I've got this error:

![capture du 2016-11-22 23-06-18](https://cloud.githubusercontent.com/assets/14202305/20544090/a6233438-b108-11e6-9894-9f7b95918ce8.png)

With these logs:

![capture du 2016-11-22 23-06-52](https://cloud.githubusercontent.com/assets/14202305/20544095/acbae9ee-b108-11e6-8924-ca8f02e37f6d.png)

If I click on yes, aftef i've got this:
![capture du 2016-11-22 23-08-10](https://cloud.githubusercontent.com/assets/14202305/20544098/b648cb70-b108-11e6-9aaf-6050f75c6f75.png)

With these logs:
![capture du 2016-11-22 23-08-25](https://cloud.githubusercontent.com/assets/14202305/20544115/bf59fdb0-b108-11e6-87bc-484ec98514e1.png)

Thank you for you're help !

**Comment by Pierre-Green** [comment]
And I only got this problem with this plugin

**Comment by Pierre-Green** [comment]
And after the engine crash

**Comment by AliakseiRusetski** [comment]
The same problem :/

**Comment by AliakseiRusetski** [comment]
I found iteresting code which contains full path to clion.exe ("C:\\Program Files (x86)\\JetBrains\\CLion 2016.2\\bin\\clion64.exe") and added my version, but it did not help me...

**Comment by AliakseiRusetski** [comment]
I've done with that. I will describe my steps to make it working. Maybe it will help you too. 

1. I did not place souce code to UE Engine Plugins folder. I cleared my old tries.
2. I created [empty] project with C++. 
3. Than made Plugins folder into the project. 
4. Placed plugin sources right there and launched [empty].uproject file. 
5. After that UE asked me "do you want recompile?", I accepted. 
6. I opened UE editor, Edit->Plugins->Project, selected Clion and pressed package. 
7. Than copied to UE/Engine/Plugins/Developer
8. And got super positive mood.
