### ISSUE TITLE
Possible race condition with current LoadingPhase "Default"

### ISSUE THREAD

**Issue by twinflyer** [dotBunny/CLionSourceCodeAccess#32]
For me (UE4.12 on Ubuntu 16.04) the plugin didn't add its menu entries because the module "LevelEditor" is not loaded at the time the plugin tries to.

The following condition just failes silently:
`if ( FModuleManager::Get().IsModuleLoaded( "LevelEditor" ) )`
 _CLionSourceCodeAccessModule.cpp:47_

Changing the LoadingPhase from Default to PostEngineInit in the *.uplugin fixed the error and the module added it's menu entries.

Thanks to Daekesh from the UE4 freenode IRC for pointing at the LoadingPhase.

**Comment by zameran** [comment]
@twinflyer, i have the same ussue on Windows 10 with UE 4.14.
LoadingPhase replacement is working.
Thanks to you and Daekesh!
