### ISSUE TITLE
Unreal editor won't compile the plugin on macOS

### ISSUE THREAD

**Issue by cesarbiods** [dotBunny/CLionSourceCodeAccess#37]
I download the plugin source, create a new folder for it next to all the plugins, paste the source, open the editor, and I always get the error message:

"Plugin 'CLionSourceCodeAccess' failed to load because module 'CLionSourceCodeAccess' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project."

I am not altering the files inside just pasting them as is but the editor won't compile the plugin. I am running macOS Sierra and unreal editor 4.14.2

**Comment by NeilConnatty** [comment]
I had the same problem, however it was solve by putting the repository files under a Plugins folder in the _project_ folder as opposed to the Unreal install folder.

**Comment by reapazor** [comment]
Currently the plugin needs to be a plugin of the project, not built into Unreal. It is definitely something I would like to look at in the future.

**Comment by fsmorygo** [comment]
I highly upvote this issue and hope it will be resolved soon.

**Comment by reapazor** [comment]
Haha :) well ... i still cant seem to resolve what your plugin does for fixing some of the annoying highlights/autocompletes. No matter what i dump into the cmakelist :)

I'm starting to evaluate the plugin again source builds of unreal to make sure that workflow is smooth, and moved to get the plugin on the marketplace so it will compile on include from there.

The problem will remain for quite sometime when there is no code in a unreal project, it doesnt start the compilation system up, so the plugin doesnt compile. Could always include compiled versions, but then were dealing with having to keep parallel with versioning.
