### ISSUE TITLE
Spaces in Project Path breaks compilation in Linux

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [dotBunny/CLionSourceCodeAccess#38]
I'm using Ubuntu Gnome 16.10 x64.

Clion couldn't compile the code if the path was something like:

    /home/user/Documents/Unreal Projects/Project Name/

Moved the project to a path without spaces and it compiles, like:

    /home/user/Documents/UnrealProjects/ProjectName/

**Comment by reapazor** [comment]
Unreal doesnt like spaces in projects normally :)  I've gotta get some time to fix this.

**Comment by RicardoEPRodrigues** [comment]
It's ironic that, by default, the engine creates a folder with a space `Documents/Unreal Projects`.

**Comment by reapazor** [comment]
It's more inside of the actual project that causes problems, the base isnt usually. I think its my bad for not handling it right outside.

**Comment by Zerophase** [comment]
Last I looked at the code, it looks like it's an unreal issue.

**Comment by reapazor** [comment]
I suspect there is a way to format the paths to handle it however, as we're doing a lot of parsing of generated files with the plugin. 

We can massage things into a format that will work :)

**Comment by reapazor** [comment]
After quickly looking into it, from the plugins end .. I'm not sure its possible to handle on the plugins side. It's been a few months since I've been in the code, so I'm totally willing to admit I'm out of it 🗡
