### ISSUE TITLE
Can't find Clion because of Visual Studio Windows 10

### ISSUE THREAD

**Issue by ItsaPerryBob** [dotBunny/CLionSourceCodeAccess#42]
It is irritating, just bought CLion and wanted to use Clion on Windows with UE4.. Please fix this.

I followed all the instructions at your Tutorial wiki, but it wont let me cause it says VISUAL STUDIO NEEDED...

**Comment by reapazor** [comment]
Did your project compile the plugin?
We as a studio natively use Macs (I know crazy), so our ability and time to debug the windows side of things is limited (hence why the lovely folks at JetBrains have helped out). You could always debug and make a PR, support the community, get that warm and fuzzy feeling ...

**Comment by reapazor** [comment]
I'm gonna close this I suspect it is tied to it being not a code project
https://github.com/dotBunny/CLionSourceCodeAccess/wiki
