### ISSUE TITLE
Freeze for 10 min when swapping source/header (aka the 'Related Symbol' action)

### ISSUE THREAD

**Issue by JesseVanDis** [dotBunny/CLionSourceCodeAccess#43]
CLion is freezes when doing the 'Related Symbol' action

in they keymap menu: 
_Main menu -> Navigate -> Related Symbol_

This does not happen in projects that are not using the CLionSourceCodeAccess plugin. 

No (error) messages occur in the terminal from which i run CLion

I use this action frequently so it would be great if this could be fixed

My OS is: ubuntu 15.10 64-bit
My CLion version is: CLion 2016.3.2 (Build #CL-163.10154.43, built on December 21, 2016)

**Comment by RicardoEPRodrigues** [comment]
So the plugin is causing the freeze?

I also suffer from this. I noticed that it only happens when switching from the .h to the .cpp file.

**Comment by JesseVanDis** [comment]
@RicardoEPRodrigues yes it is indeed the plugin that causes it. Without the plugin it does not freeze
**edit:** I have not tried to do the same on an *unreal engine* project without the plugin. But I can tell that At other C++ projects that are not unreal engine projects it does not freeze

**Comment by RicardoEPRodrigues** [comment]
Can it not freeze because of the amount of files included? Unreal Engine is not small.

How can we test the plugin to know if it is the problem?

My only guess would be to generate the CMakefile, disable/uninstall the plugin and try to run the 'Related Symbol' action.

**Comment by JesseVanDis** [comment]
Ok this time I have hit shortcut key again and gave it some time to respond. 
It took about 10 minutes before it went from header -> source 

So it does not freeze, it just takes very long until it gets to the source file. 

Perhaps it is not a plugin issue after all but a CLion one. Ill update the title of this bug

**Comment by RicardoEPRodrigues** [comment]
Have you reported this to CLion?

**Comment by shpen** [comment]
I have a similar issue when attempting to generate an overwritten method. The editor will freeze for 10-15 minutes, eating up ~20% CPU. When it unfreezes, the CPU usage does not return to normal unless I restart the editor.

**Comment by reapazor** [comment]
I've seen this, and have reported a similar thing to CLion (JetBrains). It doesn't have anything to do with the plugin itself, but the operations inside of CLion/clang.
