### ISSUE TITLE
Problem with plugin, can't install

### ISSUE THREAD

**Issue by IvPod** [dotBunny/CLionSourceCodeAccess#48]
Hi!
Thank you for your job! But i have a problem: after i downloaded plugin, i created folder in \Epic Games\UE_4.13\Engine\Plugins\CLionSourceCodeAccess (there is all files from repository). Next step, i opened my Blueprints project and take a error “missing or incompatible modules in CLionSourceCodeAccess plugin – would you like to disable it? You will no longer be able to open any assets created using it.” If i choose “Yes” – “Plugin CLionSourceCodeAccess failed to load because module CLionSourceCodeAccess could not be found. …”, else “No” – “Plugin OnlineSubsystem faild to load because module OnlineSubsystem could not be found”. What can i do?
Version UE is 4.13.2

**Comment by RicardoEPRodrigues** [comment]
Hi @IvPod, the plugin is still project based and not to be placed in the Engine.

Visit [the Wiki](https://github.com/dotBunny/CLionSourceCodeAccess/wiki/Setup) for a tutorial on how to install the plugin.

Hope it helps!
