### ISSUE TITLE
NMAKE : fatal error U1077: '"nmake.exe"' : return code '0x2'

### ISSUE THREAD

**Issue by ssoher** [dotBunny/CLionSourceCodeAccess#49]
So I'm trying to build an empty UE4 C++ project through Clion. I've tried using MinGW compilers and I get the issue #35 
Now I've downloaded Clion 2017.1 and am trying the experimental msvc support. Below is the error log I'm getting upon building the fake target.

"D:\Apps\JetBrains\CLion 2016.2.3\bin\cmake\bin\cmake.exe" --build "D:\Projects\Unreal Projects\testbed\cmake-build-debug" --target testbedEditorFake --
Scanning dependencies of target testbedEditorFake
[ 16%] Building CXX object CMakeFiles/testbedEditorFake.dir/Plugins/CLionSourceCodeAccess/Source/CLionSourceCodeAccess/Private/CLionSettings.cpp.obj
(
cl : Command line error D8049 : cannot execute 'D:\Apps\Microsoft Visual Studio 14.0\VC\bin\c1xx.dll': command line is too long to fit in debug record
NMAKE : fatal error U1077: '"D:\Apps\Microsoft Visual Studio 14.0\VC\bin\cl.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"D:\Apps\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"D:\Apps\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"D:\Apps\Microsoft Visual Studio 14.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

**Comment by luoqiang-sky** [comment]
emmm.....have you solved this problem , my friend ?

**Comment by ssoher** [comment]
Moving to MSYS2 as the updated readme recommends fixed it for me. 
Follow the instructions in the "IMPORTANT" section below.
https://github.com/dotBunny/CLionSourceCodeAccess
