### ISSUE TITLE
Goto Source Code from Blueprints passes incorrect path

### ISSUE THREAD

**Issue by reapazor** [dotBunny/CLionSourceCodeAccess#60]

**Comment by RicardoEPRodrigues** [comment]
When creating a new class and clicking on the `.h` of a parent to open it on IDE also fails.

**Comment by reapazor** [comment]
Im guessing i am missing an overload :)

**Comment by reapazor** [comment]
Fixed in 81ee47de33bf533af13a45ac77a8a0bb13a0b3af
