### ISSUE TITLE
Unreal Engine 4.16 on Windows

### ISSUE THREAD

**Issue by AzazKamaz** [dotBunny/CLionSourceCodeAccess#64]
There is an "IMPORTANT" section in README.md.
Is says, that this plugin can not work on Wondows host.
But for me, it works:
I have installed [msys2 x86_64](http://www.msys2.org) with clang ( `mingw64/mingw-w64-x86_64-clang` )
And I have changed CMakeLists.txt:
    Because i have installed UE4 on non system drive, I need to change string `set(BUILD cd "${MONO_ROOT_PATH}")` to `set(BUILD cd /d "${MONO_ROOT_PATH}")`
![pluginsettings](https://user-images.githubusercontent.com/12931951/28126690-64416942-6754-11e7-9a0c-3a7a0da965e5.png)

**Comment by filipeuva** [comment]
Hey AzazKamaz, what's your CLion run configuration like ? Can you share a screenshot of it ? Can you debug with gdb ? Thanks in advance :)

**Comment by AzazKamaz** [comment]
![image](https://user-images.githubusercontent.com/12931951/28827009-632d0ad2-76f6-11e7-80d3-5a7f9e7aeb9f.png)

**Comment by MamkinXachker** [comment]
щк
