### ISSUE TITLE
Add support for engine plugin instead of project only

### ISSUE THREAD

**Issue by Alexandertyler-zz** [dotBunny/CLionSourceCodeAccess#66]
I struggled getting this set up because the plugin doesn't get built if it's an engine level plugin instead of project level. Is there a way to add support for this? I'll look into it myself as well, because setting up the config for every project would be a hassle.

**Comment by reapazor** [comment]
Engine level support is added in our collaboration efforts with JetBrains and Epic.
https://github.com/EpicGames/UnrealEngine/pull/4142
Look to see it in a forthcoming version of UE
