### ISSUE TITLE
Class 'UWorld' doesn't have a function

### ISSUE THREAD

**Issue by agadelshin** [dotBunny/CLionSourceCodeAccess#78]
Hello.

I just installed CLion 2017.2 to work with UE4 (4.17.1) on MacOS 10.12.6. Great work!

But I'm seeing errors about methods of UWorld. CLion says 'Uworld doesn't have a function' and when I'm trying to go to function declaration, I'm seeing 'Cannot find declaration to go to'. 

It was fixed after I added ```#include "Engine/World.h"```. There was no errors from compiler, so it is IDE issue.

Same errors was for UPrimitiveComponent methods. I'm just learning UE4 and c++, but I think IDE doesn't indexing Runtime/Engine/Classes correctly, that's why I need to include headers explicitly. It may be connected with https://docs.unrealengine.com/latest/INT/Programming/UnrealBuildSystem/IWYUReferenceGuide/

XCode has autocomplete for classes before include them to source code.

Also, I can't build project - https://pastebin.com/t1iCFYBy

**Comment by reapazor** [comment]
Did you install from the repository or from the Marketplace? After over a month of waiting, Epic approved the 4.17 update of the plugin yesterday.

Did you create the project file from inside UE?

--
Matthew Davey
dotBunny

**Comment by agadelshin** [comment]
No! I installed plugin from source, cloned repo to project Plugins directory.

I created project file from inside UE.

**Comment by agadelshin** [comment]
I installed from marketplace, can't build from CLion, same errors. I'm waiting for "updating symbols" to check errors in IDE.

**Comment by agadelshin** [comment]
<img width="825" alt="2017-10-02 14 17 46" src="https://user-images.githubusercontent.com/1574361/31075093-8816e816-a77c-11e7-8c91-d48252c8fa95.png">

same issue

Also Error in macro substitution in GENERATED_BODY()

<img width="754" alt="2017-10-02 14 22 59" src="https://user-images.githubusercontent.com/1574361/31075249-4a2bf298-a77d-11e7-8f29-c2240d11269c.png">
