### ISSUE TITLE
Should we push a 4.18 update?

### ISSUE THREAD

**Issue by Alexandertyler-zz** [dotBunny/CLionSourceCodeAccess#86]
@reapazor I fixed the build issues for 4.18 in my local branch but given that you're rewriting the cmake generation for 4.19, should I open a PR? CodeLite generation seems to be borked in 4.18 so creating the CMake lists is entirely nonfunctional on my Win64 version. I think that pushing a 4.18 update would be pointless given that it doesn't actually work.

**Comment by reapazor** [comment]
Correct :) 

Tis why I haven't pushed anything for 4.18 into this repository. Early 4.18 didn't have a borked CodeLite it was introduced late stage during development.

All is well in the PR for 4.19 where the CMakeGenerator does all the heavy lifting for us now.

**Comment by Alexandertyler-zz** [comment]
Awesome, thanks man. Do you put up the PR's for review early? I saw that there were a couple to-dos in the source still.

**Comment by reapazor** [comment]
The working PR is https://github.com/EpicGames/UnrealEngine/pull/4142 
(you need to have access to the Unreal source to see it, their website has a process to get it)

The fine folks at JetBrains have committed to getting the necessary feature inline for "SaveAllDocuments" in the 2017.3 release. It's in the comments of the plugin in the PR.

The only other feature that isn't completed currently is when you make new files and they are to be added manually to the make generation system. I might tackle at the start of this week.

**Comment by Alexandertyler-zz** [comment]
Ok, so it looks like moving forward all feature development will be pushed to the UE repo for the plugin to be updated directly, correct? Which would mean that this repo is deprecated or at least at parity with the plugin. Also, thanks for taking the time to answer these questions.

**Comment by reapazor** [comment]
This repository will be depreciated, but left in tact to support <= 4.17., and of course for posterity. Feature parity for older versions is most likely not going to be maintained moving forward.

The plugin will be included with UE for distribution (hopefully 4.19) moving forward.
I will continue to contribute to and maintain the plugin within the UE master repository as needed.

RE Answering: anytime :) we're all about the community!
