### ISSUE TITLE
No compiler was found. In order to use a C++ template, you must first install NullSourceCodeAccessor. 

### ISSUE THREAD

**Issue by palmenros** [dotBunny/CLionSourceCodeAccess#93]
My system is Arch Linux with KDE, and I installed UE 4.18.3.
After installing it, I could create both Blueprint and C++ projects. I created a C++ project and build the plugin as said in the wiki. Then I changed the settings of Source Code Accessor, as said in the setup page. However, when I restarted the editor, the compile button was not there, and I couldn't open the C++ classes, so I deleted that project and I tried to create another C++ project.
I expected to be able to created a project, but I was greeted by a `No compiler was found. In order to use a C++ template, you must first install NullSourceCodeAccessor. Download NullSourceCodeAccessor`. `Download NullSourceCodeAccessor` is a link that redirects me to the wikipedia page of IDEs.
I've tried reinstalling UE4 and CLion, but that message doesn't go away.
Now I cannot create a C++ project.
Thank you

**Comment by RicardoEPRodrigues** [comment]
I believe this is a problem with UE4 and not the plugin. Check the UE4 bugs, maybe there is already someone with the same problem. [How to report a bug](https://www.unrealengine.com/en-US/support/report-a-bug)

From my experience I would recommend a reinstall and checking to see if `c++`, `g++` and `clang++` are installed. You could also try to debug the code to see the true error in Debug.

Best of luck.

**Comment by palmenros** [comment]
Well, I have solved it changing the Source Code Accessor from other Blueprint Project to which I added a C++ class and manually compiled. I no longer have that problem, but it was caused by this plugin, as it didn't happen before installing it.

**Comment by RicardoEPRodrigues** [comment]
Oh... Did you try to delete the derivative folders? Maybe your problem was there.

If it is solved then please close this issue. 😄
